### ISSUE TITLE
Change task-details patch method to only allow clients to change certain fields

### ISSUE THREAD

**Issue by lilyosah** [Quill-ToDo/App#21]
**Is your feature request related to a problem? Please describe.**
I think users may be able to use the API to change fields of tasks that they shouldn't be able to access via patch requests.

**Describe the solution you'd like**
An error to be thrown and no changes to be made if the user attempts to change the

- id
- completed_date
- date_changed

I think this should be done in the patch method in the views.py file for tasks.

I think checks for things like the start date coming before the due date can be done via model validations, so may not be part of this issue.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by bcchin** [comment]
- Need to throw an error message if they attempt to modify updated_at or created_at
- Need to throw an error message if they attempt to create a task with an id
