### ISSUE TITLE
Automate initializing PostgreSQL DB

### ISSUE THREAD

**Issue by bcchin** [Quill-ToDo/App#69]
- Should run `setup.sql`

**Comment by lilyosah** [comment]
I have a script working that does this for Windows, I'm not sure how different it will be for Unix-like systems. 

I added it as a NPM script so we'd run it from the main folder using `npm run init-be`. It's in my calendar branch though. 
This is what it looks like: `workon quill && pip install -r requirements.txt && pg_ctl start && chcp 1252 && psql -d postgres -a -f setup.sql && py manage.py makemigrations && py manage.py migrate && exit 0`
